function tableout = importfile1(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE1 Import data from a spreadsheet
%   DATA = IMPORTFILE1(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = IMPORTFILE1(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE1(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   pruebaMCSth = importfile1('prueba_MCS_th.xlsx','Sheet 1',2,5477);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2023/09/05 12:58:32

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 5477;
end

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread(workbookFile, sheetName, sprintf('A%d:AF%d',startRow(1),endRow(1)),'' , @convertSpreadsheetExcelDates);
for block=2:length(startRow)
    [~, ~, tmpRawBlock,tmpDateNumBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:AF%d',startRow(block),endRow(block)),'' , @convertSpreadsheetExcelDates);
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
    dates = [dates;tmpDateNumBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
raw = raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,30,31,32]);
dates = dates(:,29);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),dates); % Find non-numeric cells
dates(R) = {NaN}; % Replace non-numeric Excel dates with NaN

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.guilas = data(:,1);
tableout.Almera = data(:,2);
tableout.Garrucha = data(:,3);
tableout.Mazarrn = data(:,4);
tableout.ArenysdeMar = data(:,5);
tableout.Barcelona = data(:,6);
tableout.Blanes = data(:,7);
tableout.Calpe = data(:,8);
tableout.Cartagena = data(:,9);
tableout.Denia = data(:,10);
tableout.Jvea = data(:,11);
tableout.Palams = data(:,12);
tableout.Roses = data(:,13);
tableout.SantaPola = data(:,14);
tableout.Tarragona = data(:,15);
tableout.VilanovaylaGeltr = data(:,16);
tableout.Villajoyosa = data(:,17);
tableout.Alcudia = data(:,18);
tableout.Andraitx = data(:,19);
tableout.CalaRatjada = data(:,20);
tableout.Ciudadela = data(:,21);
tableout.Formentera = data(:,22);
tableout.Ibiza = data(:,23);
tableout.Mahn = data(:,24);
tableout.PalmadeMallorca = data(:,25);
tableout.SanAntonioAbad = data(:,26);
tableout.Santanyi = data(:,27);
tableout.Sller = data(:,28);
dates(~cellfun(@(x) isnumeric(x) || islogical(x), dates)) = {NaN};
tableout.fecha = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
tableout.year = data(:,29);
tableout.month = data(:,30);
tableout.day = data(:,31);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% tableout.fecha=datenum(tableout.fecha);

